### ISSUE TITLE
How to download Satellite Images

### ISSUE THREAD

**Issue by shreygarg17** [agarwalt/satimage#3]
Sir, I am having difficulty downloading satellite images of the size 1920 by 1920. I have also generated the google static maps API key but I don't know the exact syntax to write in the URL field.  I have been able to download images from other sources but they don't fit the required size criteria.

**Comment by mani-shailesh** [comment]
https://developers.google.com/maps/documentation/maps-static/dev-guide has a list of supported parameters in the Google Maps Static API. From what I remember, the largest size image returned by this API is 640 x 640. We collated 9 such images of adjacent regions to form each 1920 x 1920 image.
